name: build

on:
  push:
    branches:
        - hexo-source

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
          node-version: "12.x"

    - name: Setup env
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan e.coding.net >> ~/.ssh/known_hosts

        # set git infomation
        git config --global user.name 'liupeixin'
        git config --global user.email 'fengyi.mail@gmail.com'

    - name: Cache NPM dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --production

    - name: Deploy
      run: |
        # publish
        yarn clean && yarn build && yarn deploy

    - name: Commit cache
      run: |
        git status | grep "db.json" && git add db.json || echo "db.json no changes"
        git status | grep "source/leancloud.memo" && git add source/leancloud.memo  || echo "leancloud.memo no changes"
        git status | grep "Changes to be committed:" && git commit -m "[ci skip]: update cache" || echo "nothing to commit"
        remote_repo="git@github.com:${GITHUB_REPOSITORY}.git"
        git status | grep "nothing to commit, working tree clean" && git push "${remote_repo}" HEAD:hexo-source || echo "nothing to push"
